import type { Theme } from '@/types/theme';

export const blueprintTheme: Theme = {
  id: 'blueprint',
  name: 'Blueprint',
  description: 'A wireframe-inspired theme with off-white paper backgrounds, black ink type, and thin architectural borders. Smart home meets sketchbook.',
  version: '1.0.0',
  author: 'AI/UI Lab',
  dateAdded: '2026-03-27',
  personality: ['wireframe', 'architectural', 'technical', 'clean'],
  useCases: ['IoT dashboards', 'Smart home', 'Technical tools', 'Wireframe prototypes'],

  structure: {
    backgroundTexture: 'none',
    sectionGap: '20px',
    contentRadius: '16px',
  },

  colors: {
    primary: {
      value: '#1A1A1A',
      role: 'Main interactive color',
      usage: 'Primary buttons, active nav items, focused inputs, links',
      contrastWith: ['#F0EDE4', '#E8E4DA'],
      shades: {
        50: '#F5F5F5', 100: '#E8E8E8', 200: '#D0D0D0',
        300: '#B0B0B0', 400: '#888888', 500: '#666666',
        600: '#4A4A4A', 700: '#333333', 800: '#1A1A1A',
        900: '#0A0A0A',
      },
    },
    secondary: {
      value: '#333333',
      role: 'Secondary interactive color',
      usage: 'Secondary buttons, emphasis text, dark accents',
      contrastWith: ['#F0EDE4'],
      shades: {
        50: '#F5F5F5', 100: '#E8E8E8', 200: '#D0D0D0',
        300: '#B0B0B0', 400: '#888888', 500: '#666666',
        600: '#4A4A4A', 700: '#333333', 800: '#1A1A1A',
        900: '#0A0A0A',
      },
    },
    accent: {
      value: '#1A1A1A',
      role: 'Accent highlight color',
      usage: 'Active tabs, indicators, underlines',
      contrastWith: ['#F0EDE4'],
    },
    background: {
      value: '#F0EDE4',
      role: 'Page background',
      usage: 'Main page background, off-white paper tone',
    },
    surface: {
      value: '#F0EDE4',
      role: 'Card and panel surface',
      usage: 'Cards, panels, modals, dropdowns, table rows',
    },
    surfaceAlt: {
      value: '#E8E4DA',
      role: 'Alternate surface',
      usage: 'Alternating table rows, code blocks, input backgrounds',
    },
    border: {
      value: '#C8C4BA',
      role: 'Standard border',
      usage: 'Card borders, input borders, dividers, table borders',
    },
    borderLight: {
      value: '#D8D4CA',
      role: 'Subtle border',
      usage: 'Light separators, hover state borders',
    },
    text: {
      primary: {
        value: '#1A1A1A',
        role: 'Primary text',
        usage: 'Headings, body text, labels',
      },
      secondary: {
        value: '#5A5A52',
        role: 'Secondary text',
        usage: 'Descriptions, secondary labels, timestamps',
      },
      muted: {
        value: '#9A968C',
        role: 'Muted text',
        usage: 'Placeholders, disabled text, captions',
      },
      inverse: {
        value: '#F0EDE4',
        role: 'Inverse text',
        usage: 'Text on dark/primary backgrounds',
      },
    },
    semantic: {
      success: {
        value: '#1A1A1A',
        role: 'Success state',
        usage: 'Success badges, positive indicators',
      },
      warning: {
        value: '#5A5A52',
        role: 'Warning state',
        usage: 'Warning badges, caution indicators',
      },
      error: {
        value: '#1A1A1A',
        role: 'Error state',
        usage: 'Error badges, destructive actions',
      },
      info: {
        value: '#5A5A52',
        role: 'Info state',
        usage: 'Info badges, informational messages',
      },
    },
  },

  typography: {
    fonts: {
      heading: {
        family: 'DM Sans',
        fallback: 'system-ui, -apple-system, sans-serif',
        role: 'Headings only — H1 through H3, large display numbers',
        weights: [400, 500, 700],
      },
      body: {
        family: 'DM Sans',
        fallback: 'system-ui, -apple-system, sans-serif',
        role: 'Body text, labels, descriptions',
        weights: [400, 500, 600],
      },
      mono: {
        family: 'JetBrains Mono',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Code, data, timestamps',
        weights: [400, 500],
      },
    },
    scale: {
      xs: { size: '10px', lineHeight: '14px' },
      sm: { size: '12px', lineHeight: '18px' },
      base: { size: '14px', lineHeight: '22px' },
      lg: { size: '16px', lineHeight: '24px' },
      xl: { size: '20px', lineHeight: '28px' },
      '2xl': { size: '28px', lineHeight: '34px' },
      '3xl': { size: '38px', lineHeight: '44px' },
      '4xl': { size: '52px', lineHeight: '56px' },
    },
  },

  spacing: {
    baseUnit: '4px',
    scale: {
      '0.5': '2px', '1': '4px', '1.5': '6px', '2': '8px', '2.5': '10px', '3': '12px', '4': '16px',
      '5': '20px', '6': '24px', '8': '32px', '10': '40px',
      '12': '48px', '16': '64px', '20': '80px',
    },
    layout: {
      sidebarWidth: '240px',
      sidebarCollapsedWidth: '64px',
      topNavHeight: '56px',
      contentMaxWidth: '1280px',
      pagePadding: '28px',
    },
  },

  radius: {
    none: '0px',
    sm: { value: '4px', usage: 'Badges, tags, small chips' },
    md: { value: '8px', usage: 'Inputs, buttons, small cards' },
    lg: { value: '16px', usage: 'Cards, panels, dropdowns' },
    xl: { value: '20px', usage: 'Modals, large containers' },
    '2xl': { value: '28px', usage: 'Feature sections, hero blocks' },
    full: { value: '9999px', usage: 'Pills, avatars, toggles' },
  },

  shadows: {
    none: { value: 'none', usage: 'Flat elements' },
    sm: { value: 'none', usage: 'No shadow — wireframe style' },
    md: { value: 'none', usage: 'No shadow — wireframe style' },
    lg: { value: '0 4px 12px rgba(26,26,26,0.06)', usage: 'Dropdowns only' },
    xl: { value: '0 8px 20px rgba(26,26,26,0.08)', usage: 'Modals only' },
    overlay: {
      value: '0 0 0 1px rgba(26,26,26,0.08), 0 12px 30px rgba(26,26,26,0.08)',
      usage: 'Full overlay shadow',
    },
  },

  motion: {
    duration: {
      instant: '0ms',
      fast: '80ms',
      normal: '150ms',
      slow: '250ms',
      deliberate: '400ms',
    },
    easing: {
      standard: { value: 'cubic-bezier(0.4, 0, 0.2, 1)', feel: 'Smooth, precise' },
      enter: { value: 'cubic-bezier(0, 0, 0.2, 1)', feel: 'Decelerate in' },
      exit: { value: 'cubic-bezier(0.4, 0, 1, 1)', feel: 'Accelerate out' },
      spring: { value: 'cubic-bezier(0.34, 1.56, 0.64, 1)', feel: 'Slight overshoot' },
    },
  },

  components: {
    button: {
      primary: {
        background: '#1A1A1A',
        color: '#F0EDE4',
        border: '1px solid #1A1A1A',
        borderRadius: '9999px',
        padding: '10px 24px',
        fontSize: '14px',
        fontWeight: '600',
        hoverBackground: '#333333',
        hoverColor: '#F0EDE4',
        activeBackground: '#0A0A0A',
        disabledBackground: '#C8C4BA',
        disabledColor: '#9A968C',
      },
      secondary: {
        background: 'transparent',
        color: '#1A1A1A',
        border: '1px solid #C8C4BA',
        borderRadius: '9999px',
        padding: '10px 24px',
        fontSize: '14px',
        fontWeight: '500',
        hoverBackground: '#E8E4DA',
        hoverColor: '#1A1A1A',
        activeBackground: '#D8D4CA',
        disabledBackground: 'transparent',
        disabledColor: '#9A968C',
      },
      ghost: {
        background: 'transparent',
        color: '#5A5A52',
        border: 'none',
        borderRadius: '8px',
        padding: '10px 20px',
        fontSize: '14px',
        fontWeight: '500',
        hoverBackground: '#E8E4DA',
        hoverColor: '#1A1A1A',
        activeBackground: '#D8D4CA',
        disabledBackground: 'transparent',
        disabledColor: '#9A968C',
      },
      danger: {
        background: '#1A1A1A',
        color: '#F0EDE4',
        border: '1px solid #1A1A1A',
        borderRadius: '9999px',
        padding: '10px 24px',
        fontSize: '14px',
        fontWeight: '600',
        hoverBackground: '#333333',
        hoverColor: '#F0EDE4',
        activeBackground: '#0A0A0A',
        disabledBackground: '#C8C4BA',
        disabledColor: '#9A968C',
      },
    },
    input: {
      background: 'transparent',
      color: '#1A1A1A',
      border: '1px solid #C8C4BA',
      borderFocus: '1px solid #1A1A1A',
      borderRadius: '9999px',
      padding: '10px 16px',
      placeholder: '#9A968C',
      fontSize: '14px',
    },
    card: {
      background: '#F0EDE4',
      border: '1px solid #C8C4BA',
      borderRadius: '16px',
      shadow: 'none',
      padding: '24px',
      hoverEffect: 'none',
    },
    badge: {
      borderRadius: '4px',
      padding: '2px 8px',
      fontSize: '11px',
      fontWeight: '700',
    },
    sidebar: {
      background: '#F0EDE4',
      color: '#5A5A52',
      activeBackground: 'transparent',
      activeColor: '#1A1A1A',
      activeStyle: 'indicator',
      hoverBackground: '#E8E4DA',
      borderRight: '1px solid #C8C4BA',
      navItemRadius: '6px',
      navGap: '2px',
    },
    topNav: {
      background: '#F0EDE4',
      color: '#1A1A1A',
      borderBottom: '1px solid #C8C4BA',
      shadow: 'none',
    },
    table: {
      headerBackground: '#E8E4DA',
      headerColor: '#5A5A52',
      rowBackground: '#F0EDE4',
      rowAltBackground: '#E8E4DA',
      rowHoverBackground: '#D8D4CA',
      borderColor: '#C8C4BA',
    },
    dropdown: {
      background: '#F0EDE4',
      border: '1px solid #C8C4BA',
      shadow: '0 4px 12px rgba(26,26,26,0.06)',
      itemHover: '#E8E4DA',
      borderRadius: '12px',
    },
    modal: {
      background: '#F0EDE4',
      overlayBackground: 'rgba(26,26,26,0.3)',
      borderRadius: '20px',
      shadow: '0 8px 20px rgba(26,26,26,0.08)',
    },
    tooltip: {
      background: '#1A1A1A',
      color: '#F0EDE4',
      borderRadius: '6px',
    },
  },

  aiInstructions: {
    summary: 'A wireframe-inspired theme with off-white paper tones, black ink type, and thin architectural borders. No shadows on cards — structure is conveyed through borders alone.',
    personality: ['wireframe', 'architectural', 'technical', 'clean'],
    doList: [
      'Apply all color tokens as CSS custom properties on :root',
      'Use DM Sans for everything — headings, body, and labels. Consistency is the wireframe aesthetic.',
      'Use pill-shaped buttons (border-radius: 9999px) for primary/secondary actions',
      'Keep cards flat — no shadows, just thin 1px borders, no hover effects',
      'Use uppercase + letter-spacing for labels and section headers',
    ],
    dontList: [
      'Do not add shadows to cards — the wireframe aesthetic relies on borders only',
      'Do not use any chromatic color — everything is grayscale on warm paper',
      'Do not use heavy font weights above 600 except for display numbers',
      'Do not round cards beyond 16px — keep the architectural precision',
    ],
    cssVariableMapping: {
      '--color-primary': '{colors.primary.value}',
      '--color-bg': '{colors.background.value}',
      '--color-surface': '{colors.surface.value}',
      '--color-border': '{colors.border.value}',
      '--color-text': '{colors.text.primary.value}',
      '--color-text-muted': '{colors.text.muted.value}',
      '--font-heading': '{typography.fonts.heading.family}',
      '--font-body': '{typography.fonts.body.family}',
      '--font-mono': '{typography.fonts.mono.family}',
      '--radius-md': '{radius.md.value}',
      '--shadow-md': '{shadows.md.value}',
      '--motion-normal': '{motion.duration.normal}',
      '--motion-easing': '{motion.easing.standard.value}',
    },
  },
};
