import type { Theme } from '@/types/theme';

export const crextioTheme: Theme = {
  id: 'crextio',
  name: 'Crextio',
  description: 'A soft, warm SaaS theme with cream-to-gold gradients and charcoal contrast cards. Modern HR dashboard aesthetic.',
  version: '1.0.0',
  author: 'AI/UI Lab',
  dateAdded: '2026-03-27',
  personality: ['soft', 'warm', 'modern', 'friendly'],
  useCases: ['HR dashboards', 'SaaS platforms', 'Team management', 'Onboarding tools'],

  structure: {
    backgroundTexture: 'none',
    sectionGap: '24px',
    contentRadius: '20px',
  },

  colors: {
    primary: {
      value: '#E8C840',
      role: 'Main interactive color',
      usage: 'Primary buttons, active nav items, focused inputs, highlights',
      contrastWith: ['#1A1A1A', '#2C2C2C'],
      shades: {
        50: '#FFFCE8', 100: '#FFF8C4', 200: '#FFF09A',
        300: '#FFE66B', 400: '#F0D442', 500: '#E8C840',
        600: '#C8A830', 700: '#A08620', 800: '#7A6618',
        900: '#5C4C10',
      },
    },
    secondary: {
      value: '#2C2C2C',
      role: 'Secondary interactive color',
      usage: 'Dark contrast cards, secondary buttons, emphasis',
      contrastWith: ['#FFFFFF', '#FDF8EC'],
      shades: {
        50: '#F5F5F5', 100: '#E8E8E8', 200: '#D4D4D4',
        300: '#B0B0B0', 400: '#888888', 500: '#666666',
        600: '#4A4A4A', 700: '#3A3A3A', 800: '#2C2C2C',
        900: '#1A1A1A',
      },
    },
    accent: {
      value: '#E8C840',
      role: 'Accent highlight color',
      usage: 'Attention indicators, tags, active pills',
      contrastWith: ['#2C2C2C'],
    },
    background: {
      value: '#F0ECE2',
      role: 'Page background',
      usage: 'Main page background, soft warm gray-cream',
    },
    surface: {
      value: '#FDF8EC',
      role: 'Card and panel surface',
      usage: 'Cards, panels, modals, dropdowns, table rows',
    },
    surfaceAlt: {
      value: '#F5EDD8',
      role: 'Alternate surface',
      usage: 'Alternating table rows, code blocks, input backgrounds',
    },
    border: {
      value: '#E0D8C4',
      role: 'Standard border',
      usage: 'Card borders, input borders, dividers, table borders',
    },
    borderLight: {
      value: '#EDE6D4',
      role: 'Subtle border',
      usage: 'Light separators, hover state borders',
    },
    text: {
      primary: {
        value: '#1A1A1A',
        role: 'Primary text',
        usage: 'Headings, body text, labels',
      },
      secondary: {
        value: '#5C5C5C',
        role: 'Secondary text',
        usage: 'Descriptions, secondary labels, timestamps',
      },
      muted: {
        value: '#9C9488',
        role: 'Muted text',
        usage: 'Placeholders, disabled text, captions',
      },
      inverse: {
        value: '#FFFFFF',
        role: 'Inverse text',
        usage: 'Text on dark/primary backgrounds',
      },
    },
    semantic: {
      success: {
        value: '#4CAF50',
        role: 'Success state',
        usage: 'Success badges, positive indicators, confirmations',
      },
      warning: {
        value: '#E8C840',
        role: 'Warning state',
        usage: 'Warning badges, caution indicators, pending states',
      },
      error: {
        value: '#E05252',
        role: 'Error state',
        usage: 'Error badges, destructive actions, validation errors',
      },
      info: {
        value: '#5C8CA8',
        role: 'Info state',
        usage: 'Info badges, informational messages, help text',
      },
    },
  },

  typography: {
    fonts: {
      heading: {
        family: 'DM Sans',
        fallback: 'system-ui, -apple-system, sans-serif',
        role: 'Headings only — H1 through H3',
        weights: [500, 700],
      },
      body: {
        family: 'DM Sans',
        fallback: 'system-ui, -apple-system, sans-serif',
        role: 'Body text, labels, descriptions',
        weights: [400, 500, 600],
      },
      mono: {
        family: 'JetBrains Mono',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Code, data, timestamps',
        weights: [400, 500],
      },
    },
    scale: {
      xs: { size: '11px', lineHeight: '16px' },
      sm: { size: '13px', lineHeight: '20px' },
      base: { size: '15px', lineHeight: '24px' },
      lg: { size: '17px', lineHeight: '28px' },
      xl: { size: '21px', lineHeight: '30px' },
      '2xl': { size: '26px', lineHeight: '34px' },
      '3xl': { size: '32px', lineHeight: '40px' },
      '4xl': { size: '40px', lineHeight: '48px' },
    },
  },

  spacing: {
    baseUnit: '4px',
    scale: {
      '0.5': '2px', '1': '4px', '1.5': '6px', '2': '8px', '2.5': '10px', '3': '12px', '4': '16px',
      '5': '20px', '6': '24px', '8': '32px', '10': '40px',
      '12': '48px', '16': '64px', '20': '80px',
    },
    layout: {
      sidebarWidth: '240px',
      sidebarCollapsedWidth: '64px',
      topNavHeight: '56px',
      contentMaxWidth: '1280px',
      pagePadding: '28px',
    },
  },

  radius: {
    none: '0px',
    sm: { value: '6px', usage: 'Badges, tags, small chips' },
    md: { value: '12px', usage: 'Inputs, buttons, small cards' },
    lg: { value: '20px', usage: 'Cards, panels, dropdowns' },
    xl: { value: '24px', usage: 'Modals, large containers' },
    '2xl': { value: '32px', usage: 'Feature sections, hero blocks' },
    full: { value: '9999px', usage: 'Pills, avatars, toggles' },
  },

  shadows: {
    none: { value: 'none', usage: 'Flat elements' },
    sm: { value: '0 1px 3px rgba(26,26,26,0.05)', usage: 'Subtle elevation' },
    md: { value: '0 4px 12px rgba(26,26,26,0.08)', usage: 'Raised cards' },
    lg: { value: '0 8px 24px rgba(26,26,26,0.1)', usage: 'Floating elements' },
    xl: { value: '0 16px 40px rgba(26,26,26,0.12)', usage: 'Modals, overlays' },
    overlay: {
      value: '0 0 0 1px rgba(26,26,26,0.04), 0 20px 40px rgba(26,26,26,0.1)',
      usage: 'Full overlay shadow',
    },
  },

  motion: {
    duration: {
      instant: '50ms',
      fast: '120ms',
      normal: '250ms',
      slow: '400ms',
      deliberate: '600ms',
    },
    easing: {
      standard: { value: 'cubic-bezier(0.4, 0, 0.2, 1)', feel: 'Smooth, friendly' },
      enter: { value: 'cubic-bezier(0, 0, 0.2, 1)', feel: 'Gentle decelerate' },
      exit: { value: 'cubic-bezier(0.4, 0, 1, 1)', feel: 'Soft accelerate' },
      spring: { value: 'cubic-bezier(0.34, 1.56, 0.64, 1)', feel: 'Bouncy, playful' },
    },
  },

  components: {
    button: {
      primary: {
        background: '#2C2C2C',
        color: '#FFFFFF',
        border: 'none',
        borderRadius: '12px',
        padding: '10px 22px',
        fontSize: '15px',
        fontWeight: '600',
        hoverBackground: '#3A3A3A',
        hoverColor: '#FFFFFF',
        activeBackground: '#1A1A1A',
        disabledBackground: '#D4D4D4',
        disabledColor: '#888888',
      },
      secondary: {
        background: '#FDF8EC',
        color: '#1A1A1A',
        border: '1px solid #E0D8C4',
        borderRadius: '12px',
        padding: '10px 22px',
        fontSize: '15px',
        fontWeight: '500',
        hoverBackground: '#F5EDD8',
        hoverColor: '#1A1A1A',
        activeBackground: '#EDE6D4',
        disabledBackground: '#FDF8EC',
        disabledColor: '#9C9488',
      },
      ghost: {
        background: 'transparent',
        color: '#5C5C5C',
        border: 'none',
        borderRadius: '12px',
        padding: '10px 22px',
        fontSize: '15px',
        fontWeight: '500',
        hoverBackground: '#F5EDD8',
        hoverColor: '#1A1A1A',
        activeBackground: '#EDE6D4',
        disabledBackground: 'transparent',
        disabledColor: '#9C9488',
      },
      danger: {
        background: '#E05252',
        color: '#FFFFFF',
        border: 'none',
        borderRadius: '12px',
        padding: '10px 22px',
        fontSize: '15px',
        fontWeight: '600',
        hoverBackground: '#CC4444',
        hoverColor: '#FFFFFF',
        activeBackground: '#B83838',
        disabledBackground: '#F5CFC4',
        disabledColor: '#FFFFFF',
      },
    },
    input: {
      background: '#FDF8EC',
      color: '#1A1A1A',
      border: '1px solid #E0D8C4',
      borderFocus: '1px solid #E8C840',
      borderRadius: '12px',
      padding: '10px 14px',
      placeholder: '#9C9488',
      fontSize: '15px',
    },
    card: {
      background: '#FDF8EC',
      border: '1px solid #EDE6D4',
      borderRadius: '20px',
      shadow: '0 1px 3px rgba(26,26,26,0.05)',
      padding: '24px',
      hoverEffect: 'lift',
    },
    badge: {
      borderRadius: '9999px',
      padding: '4px 12px',
      fontSize: '12px',
      fontWeight: '600',
    },
    sidebar: {
      background: '#FDF8EC',
      color: '#5C5C5C',
      activeBackground: '#2C2C2C',
      activeColor: '#FFFFFF',
      activeStyle: 'filled',
      hoverBackground: '#F5EDD8',
      borderRight: '1px solid #E0D8C4',
      navItemRadius: '12px',
      navGap: '4px',
    },
    topNav: {
      background: '#FDF8EC',
      color: '#1A1A1A',
      borderBottom: '1px solid #EDE6D4',
      shadow: 'none',
    },
    table: {
      headerBackground: '#F5EDD8',
      headerColor: '#5C5C5C',
      rowBackground: '#FDF8EC',
      rowAltBackground: '#F5EDD8',
      rowHoverBackground: '#EDE6D4',
      borderColor: '#E0D8C4',
    },
    dropdown: {
      background: '#FDF8EC',
      border: '1px solid #E0D8C4',
      shadow: '0 8px 24px rgba(26,26,26,0.1)',
      itemHover: '#F5EDD8',
      borderRadius: '12px',
    },
    modal: {
      background: '#FDF8EC',
      overlayBackground: 'rgba(26,26,26,0.4)',
      borderRadius: '24px',
      shadow: '0 16px 40px rgba(26,26,26,0.12)',
    },
    tooltip: {
      background: '#2C2C2C',
      color: '#FFFFFF',
      borderRadius: '8px',
    },
  },

  aiInstructions: {
    summary: 'A soft, warm SaaS theme with cream-to-gold tones and charcoal contrast. Large rounded corners, friendly typography, and a modern dashboard aesthetic.',
    personality: ['soft', 'warm', 'modern', 'friendly'],
    doList: [
      'Apply all color tokens as CSS custom properties on :root',
      'Use large border radii (12px–24px) for a soft, approachable feel',
      'Use dark charcoal (#2C2C2C) for primary buttons and contrast elements',
      'Gold/yellow (#E8C840) for highlights, active pills, and accents',
    ],
    dontList: [
      'Do not use pure white backgrounds — prefer warm cream (#FDF8EC)',
      'Do not use sharp corners — maintain the soft rounded aesthetic',
      'Do not use heavy borders — keep them subtle (1px, warm tones)',
      'Do not use cool grays — all neutrals should be warm',
    ],
    cssVariableMapping: {
      '--color-primary': '{colors.primary.value}',
      '--color-bg': '{colors.background.value}',
      '--color-surface': '{colors.surface.value}',
      '--color-border': '{colors.border.value}',
      '--color-text': '{colors.text.primary.value}',
      '--color-text-muted': '{colors.text.muted.value}',
      '--font-heading': '{typography.fonts.heading.family}',
      '--font-body': '{typography.fonts.body.family}',
      '--font-mono': '{typography.fonts.mono.family}',
      '--radius-md': '{radius.md.value}',
      '--shadow-md': '{shadows.md.value}',
      '--motion-normal': '{motion.duration.normal}',
      '--motion-easing': '{motion.easing.standard.value}',
    },
  },
};
