import type { Theme } from '@/types/theme';

export const cyberTheme: Theme = {
  id: 'cyber',
  name: 'CyberOS',
  description: 'A retro terminal theme with amber phosphor on black. Monospaced type, sharp borders, and CRT nostalgia.',
  version: '1.0.0',
  author: 'AI/UI Lab',
  dateAdded: '2026-03-27',
  personality: ['retro', 'terminal', 'hacker', 'monospace'],
  useCases: ['Developer tools', 'Terminal UIs', 'Hacker dashboards', 'Retro apps'],

  structure: {
    backgroundTexture: 'none',
    sectionGap: '24px',
    contentRadius: '0px',
  },

  colors: {
    primary: {
      value: '#F5A623',
      role: 'Main interactive color',
      usage: 'Primary buttons, active nav items, focused inputs, links',
      contrastWith: ['#0D0D0D', '#1A1400'],
      shades: {
        50: '#FFF8E7', 100: '#FFEFC4', 200: '#FFE09A',
        300: '#FFCE6B', 400: '#F5A623', 500: '#E09000',
        600: '#C07800', 700: '#9A6000', 800: '#7A4C00',
        900: '#5C3900',
      },
    },
    secondary: {
      value: '#F5A623',
      role: 'Secondary interactive color',
      usage: 'Secondary buttons, emphasis text, accents',
      contrastWith: ['#0D0D0D'],
      shades: {
        50: '#FFF8E7', 100: '#FFEFC4', 200: '#FFE09A',
        300: '#FFCE6B', 400: '#F5A623', 500: '#E09000',
        600: '#C07800', 700: '#9A6000', 800: '#7A4C00',
        900: '#5C3900',
      },
    },
    accent: {
      value: '#FF8C00',
      role: 'Accent highlight color',
      usage: 'Attention indicators, highlights, active states',
      contrastWith: ['#0D0D0D'],
    },
    background: {
      value: '#0D0D0D',
      role: 'Page background',
      usage: 'Main page background, content area behind cards',
    },
    surface: {
      value: '#1A1400',
      role: 'Card and panel surface',
      usage: 'Cards, panels, modals, dropdowns, table rows',
    },
    surfaceAlt: {
      value: '#241C00',
      role: 'Alternate surface',
      usage: 'Alternating table rows, code blocks, input backgrounds',
    },
    border: {
      value: '#F5A623',
      role: 'Standard border',
      usage: 'Card borders, input borders, dividers, table borders',
    },
    borderLight: {
      value: '#3D2E00',
      role: 'Subtle border',
      usage: 'Light separators, hover state borders',
    },
    text: {
      primary: {
        value: '#F5A623',
        role: 'Primary text',
        usage: 'Headings, body text, labels',
      },
      secondary: {
        value: '#C88A1A',
        role: 'Secondary text',
        usage: 'Descriptions, secondary labels, timestamps',
      },
      muted: {
        value: '#7A5C10',
        role: 'Muted text',
        usage: 'Placeholders, disabled text, captions',
      },
      inverse: {
        value: '#0D0D0D',
        role: 'Inverse text',
        usage: 'Text on amber/primary backgrounds',
      },
    },
    semantic: {
      success: {
        value: '#F5A623',
        role: 'Success state',
        usage: 'Success badges, positive indicators, confirmations',
      },
      warning: {
        value: '#FF8C00',
        role: 'Warning state',
        usage: 'Warning badges, caution indicators, pending states',
      },
      error: {
        value: '#FF4400',
        role: 'Error state',
        usage: 'Error badges, destructive actions, validation errors',
      },
      info: {
        value: '#C88A1A',
        role: 'Info state',
        usage: 'Info badges, informational messages, help text',
      },
    },
  },

  typography: {
    fonts: {
      heading: {
        family: 'JetBrains Mono',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Headings only — H1 through H3',
        weights: [700],
      },
      body: {
        family: 'JetBrains Mono',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Body text, labels, descriptions',
        weights: [400, 500, 600],
      },
      mono: {
        family: 'JetBrains Mono',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Code, data, timestamps',
        weights: [400, 500],
      },
    },
    scale: {
      xs: { size: '10px', lineHeight: '16px' },
      sm: { size: '12px', lineHeight: '18px' },
      base: { size: '13px', lineHeight: '22px' },
      lg: { size: '15px', lineHeight: '24px' },
      xl: { size: '17px', lineHeight: '26px' },
      '2xl': { size: '20px', lineHeight: '28px' },
      '3xl': { size: '24px', lineHeight: '32px' },
      '4xl': { size: '30px', lineHeight: '38px' },
    },
  },

  spacing: {
    baseUnit: '4px',
    scale: {
      '0.5': '2px', '1': '4px', '1.5': '6px', '2': '8px', '2.5': '10px', '3': '12px', '4': '16px',
      '5': '20px', '6': '24px', '8': '32px', '10': '40px',
      '12': '48px', '16': '64px', '20': '80px',
    },
    layout: {
      sidebarWidth: '220px',
      sidebarCollapsedWidth: '56px',
      topNavHeight: '48px',
      contentMaxWidth: '1280px',
      pagePadding: '24px',
    },
  },

  radius: {
    none: '0px',
    sm: { value: '0px', usage: 'Badges, tags, small chips' },
    md: { value: '0px', usage: 'Inputs, buttons, small cards' },
    lg: { value: '2px', usage: 'Cards, panels, dropdowns' },
    xl: { value: '2px', usage: 'Modals, large containers' },
    '2xl': { value: '2px', usage: 'Feature sections, hero blocks' },
    full: { value: '9999px', usage: 'Pills, avatars, toggles' },
  },

  shadows: {
    none: { value: 'none', usage: 'Flat elements' },
    sm: { value: '0 0 4px rgba(245,166,35,0.15)', usage: 'Subtle amber glow' },
    md: { value: '0 0 8px rgba(245,166,35,0.2)', usage: 'Medium amber glow' },
    lg: { value: '0 0 16px rgba(245,166,35,0.25)', usage: 'Strong amber glow' },
    xl: { value: '0 0 24px rgba(245,166,35,0.3)', usage: 'Intense amber glow' },
    overlay: {
      value: '0 0 0 1px #F5A623, 0 0 20px rgba(245,166,35,0.2)',
      usage: 'Full overlay glow',
    },
  },

  motion: {
    duration: {
      instant: '0ms',
      fast: '50ms',
      normal: '100ms',
      slow: '200ms',
      deliberate: '300ms',
    },
    easing: {
      standard: { value: 'linear', feel: 'Instant, mechanical' },
      enter: { value: 'linear', feel: 'Instant in' },
      exit: { value: 'linear', feel: 'Instant out' },
      spring: { value: 'linear', feel: 'No bounce — terminal style' },
    },
  },

  components: {
    button: {
      primary: {
        background: '#F5A623',
        color: '#0D0D0D',
        border: '1px solid #F5A623',
        borderRadius: '0px',
        padding: '8px 16px',
        fontSize: '13px',
        fontWeight: '700',
        hoverBackground: '#0D0D0D',
        hoverColor: '#F5A623',
        activeBackground: '#241C00',
        disabledBackground: '#3D2E00',
        disabledColor: '#7A5C10',
      },
      secondary: {
        background: 'transparent',
        color: '#F5A623',
        border: '1px solid #F5A623',
        borderRadius: '0px',
        padding: '8px 16px',
        fontSize: '13px',
        fontWeight: '600',
        hoverBackground: '#1A1400',
        hoverColor: '#F5A623',
        activeBackground: '#241C00',
        disabledBackground: 'transparent',
        disabledColor: '#7A5C10',
      },
      ghost: {
        background: 'transparent',
        color: '#C88A1A',
        border: 'none',
        borderRadius: '0px',
        padding: '8px 16px',
        fontSize: '13px',
        fontWeight: '500',
        hoverBackground: '#1A1400',
        hoverColor: '#F5A623',
        activeBackground: '#241C00',
        disabledBackground: 'transparent',
        disabledColor: '#7A5C10',
      },
      danger: {
        background: '#FF4400',
        color: '#0D0D0D',
        border: '1px solid #FF4400',
        borderRadius: '0px',
        padding: '8px 16px',
        fontSize: '13px',
        fontWeight: '700',
        hoverBackground: '#0D0D0D',
        hoverColor: '#FF4400',
        activeBackground: '#241C00',
        disabledBackground: '#3D2E00',
        disabledColor: '#7A5C10',
      },
    },
    input: {
      background: '#0D0D0D',
      color: '#F5A623',
      border: '1px solid #F5A623',
      borderFocus: '1px solid #FF8C00',
      borderRadius: '0px',
      padding: '8px 12px',
      placeholder: '#7A5C10',
      fontSize: '13px',
    },
    card: {
      background: '#1A1400',
      border: '1px solid #F5A623',
      borderRadius: '0px',
      shadow: 'none',
      padding: '20px',
      hoverEffect: 'glow',
    },
    badge: {
      borderRadius: '0px',
      padding: '2px 8px',
      fontSize: '11px',
      fontWeight: '700',
    },
    sidebar: {
      background: '#0D0D0D',
      color: '#C88A1A',
      activeBackground: 'transparent',
      activeColor: '#F5A623',
      activeBorder: '1px solid #F5A623',
      activeStyle: 'outlined',
      hoverBackground: '#1A1400',
      borderRight: '1px solid #F5A623',
      navItemRadius: '0px',
      navGap: '2px',
    },
    topNav: {
      background: '#0D0D0D',
      color: '#F5A623',
      borderBottom: '1px solid #F5A623',
      shadow: 'none',
    },
    table: {
      headerBackground: '#1A1400',
      headerColor: '#F5A623',
      rowBackground: '#0D0D0D',
      rowAltBackground: '#1A1400',
      rowHoverBackground: '#241C00',
      borderColor: '#3D2E00',
    },
    dropdown: {
      background: '#1A1400',
      border: '1px solid #F5A623',
      shadow: '0 0 8px rgba(245,166,35,0.2)',
      itemHover: '#241C00',
      borderRadius: '0px',
    },
    modal: {
      background: '#1A1400',
      overlayBackground: 'rgba(0,0,0,0.8)',
      borderRadius: '0px',
      shadow: '0 0 24px rgba(245,166,35,0.3)',
    },
    tooltip: {
      background: '#F5A623',
      color: '#0D0D0D',
      borderRadius: '0px',
    },
  },

  aiInstructions: {
    summary: 'A retro terminal theme with amber phosphor text on black. All fonts are monospaced, all corners are sharp, all shadows are amber glows.',
    personality: ['retro', 'terminal', 'hacker', 'monospace'],
    doList: [
      'Apply all color tokens as CSS custom properties on :root',
      'Use monospace fonts for everything — headings, body, and code',
      'Keep all border radii at 0 — sharp corners only',
      'Use amber glow shadows instead of traditional elevation shadows',
      'Buttons should invert on hover (amber bg → black bg with amber text)',
    ],
    dontList: [
      'Do not use rounded corners — this is a terminal aesthetic',
      'Do not use any color outside the amber/orange spectrum',
      'Do not use serif or sans-serif fonts — monospace only',
      'Do not use subtle shadows — either no shadow or an amber glow',
    ],
    cssVariableMapping: {
      '--color-primary': '{colors.primary.value}',
      '--color-bg': '{colors.background.value}',
      '--color-surface': '{colors.surface.value}',
      '--color-border': '{colors.border.value}',
      '--color-text': '{colors.text.primary.value}',
      '--color-text-muted': '{colors.text.muted.value}',
      '--font-heading': '{typography.fonts.heading.family}',
      '--font-body': '{typography.fonts.body.family}',
      '--font-mono': '{typography.fonts.mono.family}',
      '--radius-md': '{radius.md.value}',
      '--shadow-md': '{shadows.md.value}',
      '--motion-normal': '{motion.duration.normal}',
      '--motion-easing': '{motion.easing.standard.value}',
    },
  },
};
