import type { Theme } from '@/types/theme';

export const defaultTheme: Theme = {
  id: 'default',
  name: 'Default',
  description: 'A clean, professional SaaS theme with indigo accents. Designed for clarity and productivity.',
  version: '1.0.0',
  author: 'AI/UI Lab',
  dateAdded: '2026-03-01',
  personality: ['clean', 'professional', 'modern', 'neutral'],
  useCases: ['SaaS dashboard', 'Admin panel', 'Internal tools'],

  colors: {
    primary: {
      value: '#4F46E5',
      role: 'Main interactive color',
      usage: 'Primary buttons, active nav items, focused inputs, links',
      contrastWith: ['#FFFFFF', '#F9FAFB'],
      shades: {
        50: '#EEF2FF', 100: '#E0E7FF', 200: '#C7D2FE', 300: '#A5B4FC',
        400: '#818CF8', 500: '#6366F1', 600: '#4F46E5', 700: '#4338CA',
        800: '#3730A3', 900: '#312E81',
      },
    },
    secondary: {
      value: '#0F172A',
      role: 'Secondary interactive color',
      usage: 'Secondary buttons, emphasis text, dark accents',
      contrastWith: ['#FFFFFF'],
      shades: {
        50: '#F8FAFC', 100: '#F1F5F9', 200: '#E2E8F0', 300: '#CBD5E1',
        400: '#94A3B8', 500: '#64748B', 600: '#475569', 700: '#334155',
        800: '#1E293B', 900: '#0F172A',
      },
    },
    accent: {
      value: '#F59E0B',
      role: 'Accent highlight color',
      usage: 'Attention indicators, highlights, premium features',
      contrastWith: ['#0F172A'],
    },
    background: {
      value: '#F9FAFB',
      role: 'Page background',
      usage: 'Main page background, content area behind cards',
    },
    surface: {
      value: '#FFFFFF',
      role: 'Card and panel surface',
      usage: 'Cards, panels, modals, dropdowns, table rows',
    },
    surfaceAlt: {
      value: '#F3F4F6',
      role: 'Alternate surface',
      usage: 'Alternating table rows, code blocks, input backgrounds',
    },
    border: {
      value: '#E5E7EB',
      role: 'Standard border',
      usage: 'Card borders, input borders, dividers, table borders',
    },
    borderLight: {
      value: '#F3F4F6',
      role: 'Subtle border',
      usage: 'Light separators, hover state borders',
    },
    text: {
      primary: {
        value: '#111827',
        role: 'Primary text',
        usage: 'Headings, body text, labels',
      },
      secondary: {
        value: '#4B5563',
        role: 'Secondary text',
        usage: 'Descriptions, secondary labels, timestamps',
      },
      muted: {
        value: '#9CA3AF',
        role: 'Muted text',
        usage: 'Placeholders, disabled text, captions',
      },
      inverse: {
        value: '#FFFFFF',
        role: 'Inverse text',
        usage: 'Text on dark/primary backgrounds',
      },
    },
    semantic: {
      success: {
        value: '#10B981',
        role: 'Success state',
        usage: 'Success badges, positive indicators, confirmations',
      },
      warning: {
        value: '#F59E0B',
        role: 'Warning state',
        usage: 'Warning badges, caution indicators, pending states',
      },
      error: {
        value: '#EF4444',
        role: 'Error state',
        usage: 'Error badges, destructive actions, validation errors',
      },
      info: {
        value: '#3B82F6',
        role: 'Info state',
        usage: 'Info badges, informational messages, help text',
      },
    },
  },

  typography: {
    fonts: {
      heading: {
        family: 'Inter',
        fallback: 'system-ui, -apple-system, sans-serif',
        role: 'Headings only — H1 through H3',
        weights: [600, 700],
      },
      body: {
        family: 'Inter',
        fallback: 'system-ui, -apple-system, sans-serif',
        role: 'Body text, labels, descriptions',
        weights: [400, 500, 600],
      },
      mono: {
        family: 'JetBrains Mono',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Code, data, timestamps',
        weights: [400, 500],
      },
    },
    scale: {
      xs: { size: '11px', lineHeight: '16px' },
      sm: { size: '13px', lineHeight: '20px' },
      base: { size: '15px', lineHeight: '24px' },
      lg: { size: '17px', lineHeight: '28px' },
      xl: { size: '20px', lineHeight: '30px' },
      '2xl': { size: '24px', lineHeight: '32px' },
      '3xl': { size: '30px', lineHeight: '38px' },
      '4xl': { size: '36px', lineHeight: '44px' },
    },
  },

  spacing: {
    baseUnit: '4px',
    scale: {
      '0.5': '2px', '1': '4px', '1.5': '6px', '2': '8px', '2.5': '10px', '3': '12px', '4': '16px',
      '5': '20px', '6': '24px', '8': '32px', '10': '40px',
      '12': '48px', '16': '64px', '20': '80px',
    },
    layout: {
      sidebarWidth: '256px',
      sidebarCollapsedWidth: '64px',
      topNavHeight: '60px',
      contentMaxWidth: '1280px',
      pagePadding: '32px',
    },
  },

  radius: {
    none: '0px',
    sm: { value: '4px', usage: 'Badges, tags, small chips' },
    md: { value: '8px', usage: 'Inputs, buttons, small cards' },
    lg: { value: '12px', usage: 'Cards, panels, dropdowns' },
    xl: { value: '16px', usage: 'Modals, large containers' },
    '2xl': { value: '24px', usage: 'Feature sections, hero blocks' },
    full: { value: '9999px', usage: 'Pills, avatars, toggles' },
  },

  shadows: {
    none: { value: 'none', usage: 'Flat elements' },
    sm: { value: '0 1px 2px rgba(0,0,0,0.05)', usage: 'Subtle elevation for small elements' },
    md: { value: '0 4px 6px -1px rgba(0,0,0,0.1)', usage: 'Raised cards and panels' },
    lg: { value: '0 10px 15px -3px rgba(0,0,0,0.1)', usage: 'Floating elements, popovers' },
    xl: { value: '0 20px 25px -5px rgba(0,0,0,0.1)', usage: 'Modals, overlays' },
    overlay: {
      value: '0 0 0 1px rgba(0,0,0,0.05), 0 25px 50px -12px rgba(0,0,0,0.25)',
      usage: 'Full overlay shadow',
    },
  },

  motion: {
    duration: {
      instant: '50ms',
      fast: '100ms',
      normal: '200ms',
      slow: '350ms',
      deliberate: '500ms',
    },
    easing: {
      standard: { value: 'cubic-bezier(0.4, 0, 0.2, 1)', feel: 'Smooth, neutral' },
      enter: { value: 'cubic-bezier(0, 0, 0.2, 1)', feel: 'Decelerate in' },
      exit: { value: 'cubic-bezier(0.4, 0, 1, 1)', feel: 'Accelerate out' },
      spring: { value: 'cubic-bezier(0.34, 1.56, 0.64, 1)', feel: 'Slight overshoot' },
    },
  },

  components: {
    button: {
      primary: {
        background: '#4F46E5',
        color: '#FFFFFF',
        border: 'none',
        borderRadius: '8px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '600',
        hoverBackground: '#4338CA',
        hoverColor: '#FFFFFF',
        activeBackground: '#3730A3',
        disabledBackground: '#C7D2FE',
        disabledColor: '#FFFFFF',
      },
      secondary: {
        background: '#FFFFFF',
        color: '#111827',
        border: '1px solid #E5E7EB',
        borderRadius: '8px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '500',
        hoverBackground: '#F9FAFB',
        hoverColor: '#111827',
        activeBackground: '#F3F4F6',
        disabledBackground: '#F9FAFB',
        disabledColor: '#9CA3AF',
      },
      ghost: {
        background: 'transparent',
        color: '#4B5563',
        border: 'none',
        borderRadius: '8px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '500',
        hoverBackground: '#F3F4F6',
        hoverColor: '#111827',
        activeBackground: '#E5E7EB',
        disabledBackground: 'transparent',
        disabledColor: '#9CA3AF',
      },
      danger: {
        background: '#EF4444',
        color: '#FFFFFF',
        border: 'none',
        borderRadius: '8px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '600',
        hoverBackground: '#DC2626',
        hoverColor: '#FFFFFF',
        activeBackground: '#B91C1C',
        disabledBackground: '#FCA5A5',
        disabledColor: '#FFFFFF',
      },
    },
    input: {
      background: '#FFFFFF',
      color: '#111827',
      border: '1px solid #E5E7EB',
      borderFocus: '1px solid #4F46E5',
      borderRadius: '8px',
      padding: '10px 14px',
      placeholder: '#9CA3AF',
      fontSize: '15px',
    },
    card: {
      background: '#FFFFFF',
      border: '1px solid #E5E7EB',
      borderRadius: '12px',
      shadow: '0 1px 2px rgba(0,0,0,0.05)',
      padding: '24px',
    },
    badge: {
      borderRadius: '9999px',
      padding: '2px 10px',
      fontSize: '12px',
      fontWeight: '500',
    },
    sidebar: {
      background: '#FFFFFF',
      color: '#4B5563',
      activeBackground: '#EEF2FF',
      activeColor: '#4F46E5',
      hoverBackground: '#F9FAFB',
      borderRight: '1px solid #E5E7EB',
    },
    topNav: {
      background: '#FFFFFF',
      color: '#111827',
      borderBottom: '1px solid #E5E7EB',
      shadow: '0 1px 2px rgba(0,0,0,0.05)',
    },
    table: {
      headerBackground: '#F9FAFB',
      headerColor: '#4B5563',
      rowBackground: '#FFFFFF',
      rowAltBackground: '#F9FAFB',
      rowHoverBackground: '#F3F4F6',
      borderColor: '#E5E7EB',
    },
    dropdown: {
      background: '#FFFFFF',
      border: '1px solid #E5E7EB',
      shadow: '0 10px 15px -3px rgba(0,0,0,0.1)',
      itemHover: '#F3F4F6',
      borderRadius: '8px',
    },
    modal: {
      background: '#FFFFFF',
      overlayBackground: 'rgba(0,0,0,0.5)',
      borderRadius: '16px',
      shadow: '0 20px 25px -5px rgba(0,0,0,0.1)',
    },
    tooltip: {
      background: '#0F172A',
      color: '#FFFFFF',
      borderRadius: '6px',
    },
  },

  aiInstructions: {
    summary: 'A clean, professional SaaS theme with indigo accents. Neutral and modern with a focus on clarity and readability.',
    personality: ['clean', 'professional', 'modern', 'neutral'],
    doList: [
      'Apply all color tokens as CSS custom properties on :root',
      'Use heading font only for H1–H3, never for body copy',
      'Respect component-level overrides over generic token inference',
      'Maintain the elevation system — do not invent additional shadow values',
    ],
    dontList: [
      'Do not mix light and dark surface tokens',
      'Do not use the primary color for destructive actions — use semantic.error',
      'Do not apply border-radius.full to rectangular layout containers',
    ],
    cssVariableMapping: {
      '--color-primary': '{colors.primary.value}',
      '--color-bg': '{colors.background.value}',
      '--color-surface': '{colors.surface.value}',
      '--color-border': '{colors.border.value}',
      '--color-text': '{colors.text.primary.value}',
      '--color-text-muted': '{colors.text.muted.value}',
      '--font-heading': '{typography.fonts.heading.family}',
      '--font-body': '{typography.fonts.body.family}',
      '--font-mono': '{typography.fonts.mono.family}',
      '--radius-md': '{radius.md.value}',
      '--shadow-md': '{shadows.md.value}',
      '--motion-normal': '{motion.duration.normal}',
      '--motion-easing': '{motion.easing.standard.value}',
    },
  },
};
