import type { Theme } from '@/types/theme';

export const defaultTheme: Theme = {
  id: 'default',
  name: 'Monochrome',
  description: 'A stark black-and-white theme. Pure contrast, zero color noise. Every UI element earns its place through structure alone.',
  version: '1.0.0',
  author: 'AI/UI Lab',
  dateAdded: '2026-03-01',
  personality: ['minimal', 'stark', 'monochrome', 'typographic'],
  useCases: ['Portfolio', 'Admin panel', 'Internal tools', 'Developer dashboard'],

  structure: {
    backgroundTexture: 'none',
    sectionGap: '24px',
    contentRadius: '6px',
  },

  colors: {
    primary: {
      value: '#000000',
      role: 'Main interactive color',
      usage: 'Primary buttons, active nav items, focused inputs, links',
      contrastWith: ['#FFFFFF', '#FAFAFA'],
      shades: {
        50: '#FAFAFA', 100: '#F5F5F5', 200: '#E5E5E5', 300: '#D4D4D4',
        400: '#A3A3A3', 500: '#737373', 600: '#525252', 700: '#404040',
        800: '#262626', 900: '#171717',
      },
    },
    secondary: {
      value: '#171717',
      role: 'Secondary interactive color',
      usage: 'Secondary buttons, emphasis text, dark accents',
      contrastWith: ['#FFFFFF'],
      shades: {
        50: '#FAFAFA', 100: '#F5F5F5', 200: '#E5E5E5', 300: '#D4D4D4',
        400: '#A3A3A3', 500: '#737373', 600: '#525252', 700: '#404040',
        800: '#262626', 900: '#171717',
      },
    },
    accent: {
      value: '#525252',
      role: 'Accent highlight color',
      usage: 'Attention indicators, highlights, premium features',
      contrastWith: ['#FFFFFF'],
    },
    background: {
      value: '#FFFFFF',
      role: 'Page background',
      usage: 'Main page background, content area behind cards',
    },
    surface: {
      value: '#FFFFFF',
      role: 'Card and panel surface',
      usage: 'Cards, panels, modals, dropdowns, table rows',
    },
    surfaceAlt: {
      value: '#FAFAFA',
      role: 'Alternate surface',
      usage: 'Alternating table rows, code blocks, input backgrounds',
    },
    border: {
      value: '#E5E5E5',
      role: 'Standard border',
      usage: 'Card borders, input borders, dividers, table borders',
    },
    borderLight: {
      value: '#F5F5F5',
      role: 'Subtle border',
      usage: 'Light separators, hover state borders',
    },
    text: {
      primary: {
        value: '#0A0A0A',
        role: 'Primary text',
        usage: 'Headings, body text, labels',
      },
      secondary: {
        value: '#525252',
        role: 'Secondary text',
        usage: 'Descriptions, secondary labels, timestamps',
      },
      muted: {
        value: '#A3A3A3',
        role: 'Muted text',
        usage: 'Placeholders, disabled text, captions',
      },
      inverse: {
        value: '#FFFFFF',
        role: 'Inverse text',
        usage: 'Text on dark/primary backgrounds',
      },
    },
    semantic: {
      success: {
        value: '#171717',
        role: 'Success state',
        usage: 'Success badges, positive indicators, confirmations',
      },
      warning: {
        value: '#525252',
        role: 'Warning state',
        usage: 'Warning badges, caution indicators, pending states',
      },
      error: {
        value: '#0A0A0A',
        role: 'Error state',
        usage: 'Error badges, destructive actions, validation errors',
      },
      info: {
        value: '#404040',
        role: 'Info state',
        usage: 'Info badges, informational messages, help text',
      },
    },
  },

  typography: {
    fonts: {
      heading: {
        family: 'Inter',
        fallback: 'system-ui, -apple-system, sans-serif',
        role: 'Headings only — H1 through H3',
        weights: [600, 700],
      },
      body: {
        family: 'Inter',
        fallback: 'system-ui, -apple-system, sans-serif',
        role: 'Body text, labels, descriptions',
        weights: [400, 500, 600],
      },
      mono: {
        family: 'JetBrains Mono',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Code, data, timestamps',
        weights: [400, 500],
      },
    },
    scale: {
      xs: { size: '11px', lineHeight: '16px' },
      sm: { size: '13px', lineHeight: '20px' },
      base: { size: '15px', lineHeight: '24px' },
      lg: { size: '17px', lineHeight: '28px' },
      xl: { size: '20px', lineHeight: '30px' },
      '2xl': { size: '24px', lineHeight: '32px' },
      '3xl': { size: '30px', lineHeight: '38px' },
      '4xl': { size: '36px', lineHeight: '44px' },
    },
  },

  spacing: {
    baseUnit: '4px',
    scale: {
      '0.5': '2px', '1': '4px', '1.5': '6px', '2': '8px', '2.5': '10px', '3': '12px', '4': '16px',
      '5': '20px', '6': '24px', '8': '32px', '10': '40px',
      '12': '48px', '16': '64px', '20': '80px',
    },
    layout: {
      sidebarWidth: '256px',
      sidebarCollapsedWidth: '64px',
      topNavHeight: '60px',
      contentMaxWidth: '1280px',
      pagePadding: '32px',
    },
  },

  radius: {
    none: '0px',
    sm: { value: '2px', usage: 'Badges, tags, small chips' },
    md: { value: '4px', usage: 'Inputs, buttons, small cards' },
    lg: { value: '6px', usage: 'Cards, panels, dropdowns' },
    xl: { value: '8px', usage: 'Modals, large containers' },
    '2xl': { value: '12px', usage: 'Feature sections, hero blocks' },
    full: { value: '9999px', usage: 'Pills, avatars, toggles' },
  },

  shadows: {
    none: { value: 'none', usage: 'Flat elements' },
    sm: { value: '0 1px 2px rgba(0,0,0,0.04)', usage: 'Subtle elevation for small elements' },
    md: { value: '0 2px 4px rgba(0,0,0,0.06)', usage: 'Raised cards and panels' },
    lg: { value: '0 4px 12px rgba(0,0,0,0.08)', usage: 'Floating elements, popovers' },
    xl: { value: '0 8px 24px rgba(0,0,0,0.1)', usage: 'Modals, overlays' },
    overlay: {
      value: '0 0 0 1px rgba(0,0,0,0.04), 0 16px 40px rgba(0,0,0,0.12)',
      usage: 'Full overlay shadow',
    },
  },

  motion: {
    duration: {
      instant: '50ms',
      fast: '100ms',
      normal: '200ms',
      slow: '350ms',
      deliberate: '500ms',
    },
    easing: {
      standard: { value: 'cubic-bezier(0.4, 0, 0.2, 1)', feel: 'Smooth, neutral' },
      enter: { value: 'cubic-bezier(0, 0, 0.2, 1)', feel: 'Decelerate in' },
      exit: { value: 'cubic-bezier(0.4, 0, 1, 1)', feel: 'Accelerate out' },
      spring: { value: 'cubic-bezier(0.34, 1.56, 0.64, 1)', feel: 'Slight overshoot' },
    },
  },

  components: {
    button: {
      primary: {
        background: '#0A0A0A',
        color: '#FFFFFF',
        border: 'none',
        borderRadius: '4px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '600',
        hoverBackground: '#262626',
        hoverColor: '#FFFFFF',
        activeBackground: '#171717',
        disabledBackground: '#D4D4D4',
        disabledColor: '#FFFFFF',
      },
      secondary: {
        background: '#FFFFFF',
        color: '#0A0A0A',
        border: '1px solid #E5E5E5',
        borderRadius: '4px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '500',
        hoverBackground: '#FAFAFA',
        hoverColor: '#0A0A0A',
        activeBackground: '#F5F5F5',
        disabledBackground: '#FAFAFA',
        disabledColor: '#A3A3A3',
      },
      ghost: {
        background: 'transparent',
        color: '#525252',
        border: 'none',
        borderRadius: '4px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '500',
        hoverBackground: '#F5F5F5',
        hoverColor: '#0A0A0A',
        activeBackground: '#E5E5E5',
        disabledBackground: 'transparent',
        disabledColor: '#A3A3A3',
      },
      danger: {
        background: '#0A0A0A',
        color: '#FFFFFF',
        border: 'none',
        borderRadius: '4px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '600',
        hoverBackground: '#262626',
        hoverColor: '#FFFFFF',
        activeBackground: '#171717',
        disabledBackground: '#D4D4D4',
        disabledColor: '#FFFFFF',
      },
    },
    input: {
      background: '#FFFFFF',
      color: '#0A0A0A',
      border: '1px solid #E5E5E5',
      borderFocus: '1px solid #0A0A0A',
      borderRadius: '4px',
      padding: '10px 14px',
      placeholder: '#A3A3A3',
      fontSize: '15px',
    },
    card: {
      background: '#FFFFFF',
      border: '1px solid #E5E5E5',
      borderRadius: '6px',
      shadow: 'none',
      padding: '24px',
      hoverEffect: 'border',
    },
    badge: {
      borderRadius: '2px',
      padding: '2px 8px',
      fontSize: '12px',
      fontWeight: '600',
    },
    sidebar: {
      background: '#FAFAFA',
      color: '#525252',
      activeBackground: '#0A0A0A',
      activeColor: '#FFFFFF',
      activeStyle: 'filled',
      hoverBackground: '#F5F5F5',
      borderRight: '1px solid #E5E5E5',
      navItemRadius: '4px',
      navGap: '4px',
    },
    topNav: {
      background: '#FFFFFF',
      color: '#0A0A0A',
      borderBottom: '1px solid #E5E5E5',
      shadow: 'none',
    },
    table: {
      headerBackground: '#FAFAFA',
      headerColor: '#525252',
      rowBackground: '#FFFFFF',
      rowAltBackground: '#FAFAFA',
      rowHoverBackground: '#F5F5F5',
      borderColor: '#E5E5E5',
    },
    dropdown: {
      background: '#FFFFFF',
      border: '1px solid #E5E5E5',
      shadow: '0 4px 12px rgba(0,0,0,0.08)',
      itemHover: '#F5F5F5',
      borderRadius: '4px',
    },
    modal: {
      background: '#FFFFFF',
      overlayBackground: 'rgba(0,0,0,0.4)',
      borderRadius: '8px',
      shadow: '0 8px 24px rgba(0,0,0,0.1)',
    },
    tooltip: {
      background: '#0A0A0A',
      color: '#FFFFFF',
      borderRadius: '4px',
    },
  },

  aiInstructions: {
    summary: 'A stark black-and-white monochrome theme. Pure contrast, no color noise. Structure and typography do all the work.',
    personality: ['minimal', 'stark', 'monochrome', 'typographic'],
    doList: [
      'Apply all color tokens as CSS custom properties on :root',
      'Use heading font only for H1–H3, never for body copy',
      'Respect component-level overrides over generic token inference',
      'Keep everything in grayscale — the absence of color IS the design',
    ],
    dontList: [
      'Do not introduce any chromatic color — everything must be grayscale',
      'Do not use large border radii — keep shapes sharp and architectural',
      'Do not apply border-radius.full to rectangular layout containers',
      'Do not add shadows for decoration — use them sparingly for functional elevation only',
    ],
    cssVariableMapping: {
      '--color-primary': '{colors.primary.value}',
      '--color-bg': '{colors.background.value}',
      '--color-surface': '{colors.surface.value}',
      '--color-border': '{colors.border.value}',
      '--color-text': '{colors.text.primary.value}',
      '--color-text-muted': '{colors.text.muted.value}',
      '--font-heading': '{typography.fonts.heading.family}',
      '--font-body': '{typography.fonts.body.family}',
      '--font-mono': '{typography.fonts.mono.family}',
      '--radius-md': '{radius.md.value}',
      '--shadow-md': '{shadows.md.value}',
      '--motion-normal': '{motion.duration.normal}',
      '--motion-easing': '{motion.easing.standard.value}',
    },
  },
};
