import type { Theme } from '@/types/theme';

export const emberTheme: Theme = {
  id: 'ember',
  name: 'Ember',
  description: 'A luxurious dark theme with warm olive tones and red-orange accents. Inspired by data-rich editorial interfaces.',
  version: '1.0.0',
  author: 'AI/UI Lab',
  dateAdded: '2026-03-27',
  personality: ['dark', 'luxurious', 'warm', 'editorial'],
  useCases: ['Data dashboards', 'Analytics platforms', 'Creative tools', 'Premium apps'],

  colors: {
    primary: {
      value: '#E8430A',
      role: 'Main interactive color',
      usage: 'Primary buttons, active nav items, focused inputs, links',
      contrastWith: ['#1A1A16', '#E8E4DC'],
      shades: {
        50: '#FFF4ED', 100: '#FFE4D4', 200: '#FFC5A8',
        300: '#FF9E70', 400: '#FF6B36', 500: '#E8430A',
        600: '#D13508', 700: '#AB260A', 800: '#882010',
        900: '#6E1D10',
      },
    },
    secondary: {
      value: '#E8E4DC',
      role: 'Secondary interactive color',
      usage: 'Secondary buttons, emphasis text, light accents',
      contrastWith: ['#1A1A16'],
      shades: {
        50: '#FAFAF8', 100: '#F5F4F0', 200: '#EDEAE4',
        300: '#E0DCD3', 400: '#CBC6BA', 500: '#B0AA9D',
        600: '#8F897D', 700: '#716C63', 800: '#5A5650',
        900: '#474440',
      },
    },
    accent: {
      value: '#C9A84C',
      role: 'Accent highlight color',
      usage: 'Attention indicators, highlights, premium features',
      contrastWith: ['#1A1A16'],
    },
    background: {
      value: '#131310',
      role: 'Page background',
      usage: 'Main page background, content area behind cards',
    },
    surface: {
      value: '#1E1E1A',
      role: 'Card and panel surface',
      usage: 'Cards, panels, modals, dropdowns, table rows',
    },
    surfaceAlt: {
      value: '#26261F',
      role: 'Alternate surface',
      usage: 'Alternating table rows, code blocks, input backgrounds',
    },
    border: {
      value: '#3A3A30',
      role: 'Standard border',
      usage: 'Card borders, input borders, dividers, table borders',
    },
    borderLight: {
      value: '#2E2E26',
      role: 'Subtle border',
      usage: 'Light separators, hover state borders',
    },
    text: {
      primary: {
        value: '#E8E4DC',
        role: 'Primary text',
        usage: 'Headings, body text, labels',
      },
      secondary: {
        value: '#A8A49A',
        role: 'Secondary text',
        usage: 'Descriptions, secondary labels, timestamps',
      },
      muted: {
        value: '#6B6860',
        role: 'Muted text',
        usage: 'Placeholders, disabled text, captions',
      },
      inverse: {
        value: '#131310',
        role: 'Inverse text',
        usage: 'Text on light/primary backgrounds',
      },
    },
    semantic: {
      success: {
        value: '#4ADE80',
        role: 'Success state',
        usage: 'Success badges, positive indicators, confirmations',
      },
      warning: {
        value: '#FACC15',
        role: 'Warning state',
        usage: 'Warning badges, caution indicators, pending states',
      },
      error: {
        value: '#FB7185',
        role: 'Error state',
        usage: 'Error badges, destructive actions, validation errors',
      },
      info: {
        value: '#60A5FA',
        role: 'Info state',
        usage: 'Info badges, informational messages, help text',
      },
    },
  },

  typography: {
    fonts: {
      heading: {
        family: 'DM Serif Display',
        fallback: 'Georgia, serif',
        role: 'Headings only — H1 through H3',
        weights: [400],
      },
      body: {
        family: 'Inter',
        fallback: 'system-ui, -apple-system, sans-serif',
        role: 'Body text, labels, descriptions',
        weights: [400, 500, 600],
      },
      mono: {
        family: 'JetBrains Mono',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Code, data, timestamps',
        weights: [400, 500],
      },
    },
    scale: {
      xs: { size: '11px', lineHeight: '16px' },
      sm: { size: '13px', lineHeight: '20px' },
      base: { size: '15px', lineHeight: '24px' },
      lg: { size: '17px', lineHeight: '28px' },
      xl: { size: '20px', lineHeight: '30px' },
      '2xl': { size: '26px', lineHeight: '34px' },
      '3xl': { size: '34px', lineHeight: '42px' },
      '4xl': { size: '42px', lineHeight: '50px' },
    },
  },

  spacing: {
    baseUnit: '4px',
    scale: {
      '0.5': '2px', '1': '4px', '1.5': '6px', '2': '8px', '2.5': '10px', '3': '12px', '4': '16px',
      '5': '20px', '6': '24px', '8': '32px', '10': '40px',
      '12': '48px', '16': '64px', '20': '80px',
    },
    layout: {
      sidebarWidth: '260px',
      sidebarCollapsedWidth: '68px',
      topNavHeight: '60px',
      contentMaxWidth: '1280px',
      pagePadding: '32px',
    },
  },

  radius: {
    none: '0px',
    sm: { value: '6px', usage: 'Badges, tags, small chips' },
    md: { value: '10px', usage: 'Inputs, buttons, small cards' },
    lg: { value: '16px', usage: 'Cards, panels, dropdowns' },
    xl: { value: '20px', usage: 'Modals, large containers' },
    '2xl': { value: '28px', usage: 'Feature sections, hero blocks' },
    full: { value: '9999px', usage: 'Pills, avatars, toggles' },
  },

  shadows: {
    none: { value: 'none', usage: 'Flat elements' },
    sm: { value: '0 1px 3px rgba(0,0,0,0.4)', usage: 'Subtle elevation for small elements' },
    md: { value: '0 4px 8px -1px rgba(0,0,0,0.5)', usage: 'Raised cards and panels' },
    lg: { value: '0 12px 24px -4px rgba(0,0,0,0.5)', usage: 'Floating elements, popovers' },
    xl: { value: '0 24px 48px -8px rgba(0,0,0,0.6)', usage: 'Modals, overlays' },
    overlay: {
      value: '0 0 0 1px rgba(255,255,255,0.05), 0 25px 50px -12px rgba(0,0,0,0.6)',
      usage: 'Full overlay shadow',
    },
  },

  motion: {
    duration: {
      instant: '50ms',
      fast: '100ms',
      normal: '200ms',
      slow: '350ms',
      deliberate: '500ms',
    },
    easing: {
      standard: { value: 'cubic-bezier(0.4, 0, 0.2, 1)', feel: 'Smooth, neutral' },
      enter: { value: 'cubic-bezier(0, 0, 0.2, 1)', feel: 'Decelerate in' },
      exit: { value: 'cubic-bezier(0.4, 0, 1, 1)', feel: 'Accelerate out' },
      spring: { value: 'cubic-bezier(0.34, 1.56, 0.64, 1)', feel: 'Slight overshoot' },
    },
  },

  components: {
    button: {
      primary: {
        background: '#E8430A',
        color: '#FFFFFF',
        border: 'none',
        borderRadius: '10px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '600',
        hoverBackground: '#D13508',
        hoverColor: '#FFFFFF',
        activeBackground: '#AB260A',
        disabledBackground: '#5A2A15',
        disabledColor: '#8A7568',
      },
      secondary: {
        background: '#26261F',
        color: '#E8E4DC',
        border: '1px solid #3A3A30',
        borderRadius: '10px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '500',
        hoverBackground: '#32322A',
        hoverColor: '#E8E4DC',
        activeBackground: '#3A3A30',
        disabledBackground: '#1E1E1A',
        disabledColor: '#6B6860',
      },
      ghost: {
        background: 'transparent',
        color: '#A8A49A',
        border: 'none',
        borderRadius: '10px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '500',
        hoverBackground: '#26261F',
        hoverColor: '#E8E4DC',
        activeBackground: '#3A3A30',
        disabledBackground: 'transparent',
        disabledColor: '#6B6860',
      },
      danger: {
        background: '#DC2626',
        color: '#FFFFFF',
        border: 'none',
        borderRadius: '10px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '600',
        hoverBackground: '#B91C1C',
        hoverColor: '#FFFFFF',
        activeBackground: '#991B1B',
        disabledBackground: '#5A2020',
        disabledColor: '#8A6868',
      },
    },
    input: {
      background: '#1E1E1A',
      color: '#E8E4DC',
      border: '1px solid #3A3A30',
      borderFocus: '1px solid #E8430A',
      borderRadius: '10px',
      padding: '10px 14px',
      placeholder: '#6B6860',
      fontSize: '15px',
    },
    card: {
      background: '#1E1E1A',
      border: '1px solid #2E2E26',
      borderRadius: '16px',
      shadow: '0 1px 3px rgba(0,0,0,0.4)',
      padding: '24px',
    },
    badge: {
      borderRadius: '9999px',
      padding: '2px 10px',
      fontSize: '12px',
      fontWeight: '500',
    },
    sidebar: {
      background: '#1A1A16',
      color: '#A8A49A',
      activeBackground: 'rgba(232, 67, 10, 0.1)',
      activeColor: '#E8430A',
      hoverBackground: '#26261F',
      borderRight: '1px solid #2E2E26',
    },
    topNav: {
      background: '#1A1A16',
      color: '#E8E4DC',
      borderBottom: '1px solid #2E2E26',
      shadow: 'none',
    },
    table: {
      headerBackground: '#1A1A16',
      headerColor: '#A8A49A',
      rowBackground: '#1E1E1A',
      rowAltBackground: '#1A1A16',
      rowHoverBackground: '#26261F',
      borderColor: '#2E2E26',
    },
    dropdown: {
      background: '#1E1E1A',
      border: '1px solid #3A3A30',
      shadow: '0 12px 24px -4px rgba(0,0,0,0.5)',
      itemHover: '#26261F',
      borderRadius: '10px',
    },
    modal: {
      background: '#1E1E1A',
      overlayBackground: 'rgba(0,0,0,0.7)',
      borderRadius: '20px',
      shadow: '0 24px 48px -8px rgba(0,0,0,0.6)',
    },
    tooltip: {
      background: '#E8E4DC',
      color: '#131310',
      borderRadius: '8px',
    },
  },

  aiInstructions: {
    summary: 'A luxurious dark theme with warm olive-black backgrounds and red-orange accents. Serif headings evoke an editorial, data-rich aesthetic.',
    personality: ['dark', 'luxurious', 'warm', 'editorial'],
    doList: [
      'Apply all color tokens as CSS custom properties on :root',
      'Use serif heading font (DM Serif Display) only for H1–H3, never for body copy',
      'Use larger border radii — this theme favors soft, rounded shapes',
      'Maintain warm, muted contrast — avoid pure white (#FFF) anywhere',
    ],
    dontList: [
      'Do not use bright white backgrounds — everything should sit on dark warm surfaces',
      'Do not use the primary color for destructive actions — use semantic.error',
      'Do not use border-radius.full on rectangular layout containers',
      'Do not use cool grays — all neutrals should have a warm olive undertone',
    ],
    cssVariableMapping: {
      '--color-primary': '{colors.primary.value}',
      '--color-bg': '{colors.background.value}',
      '--color-surface': '{colors.surface.value}',
      '--color-border': '{colors.border.value}',
      '--color-text': '{colors.text.primary.value}',
      '--color-text-muted': '{colors.text.muted.value}',
      '--font-heading': '{typography.fonts.heading.family}',
      '--font-body': '{typography.fonts.body.family}',
      '--font-mono': '{typography.fonts.mono.family}',
      '--radius-md': '{radius.md.value}',
      '--shadow-md': '{shadows.md.value}',
      '--motion-normal': '{motion.duration.normal}',
      '--motion-easing': '{motion.easing.standard.value}',
    },
  },
};
