import type { Theme } from '@/types/theme';

export const oceanTheme: Theme = {
  id: 'ocean',
  name: 'Ocean',
  description: 'A calming teal and deep blue theme inspired by the sea. Cool tones with warm coral accents.',
  version: '1.0.0',
  author: 'AI/UI Lab',
  dateAdded: '2026-03-15',
  personality: ['calm', 'cool', 'professional', 'refreshing'],
  useCases: ['SaaS dashboard', 'Analytics platform', 'Health tech'],

  colors: {
    primary: {
      value: '#0D9488',
      role: 'Main interactive color',
      usage: 'Primary buttons, active nav items, focused inputs, links',
      contrastWith: ['#FFFFFF', '#F0FDFA'],
      shades: {
        50: '#F0FDFA', 100: '#CCFBF1', 200: '#99F6E4', 300: '#5EEAD4',
        400: '#2DD4BF', 500: '#14B8A6', 600: '#0D9488', 700: '#0F766E',
        800: '#115E59', 900: '#134E4A',
      },
    },
    secondary: {
      value: '#0C4A6E',
      role: 'Secondary interactive color',
      usage: 'Secondary buttons, emphasis text, dark accents',
      contrastWith: ['#FFFFFF'],
      shades: {
        50: '#F0F9FF', 100: '#E0F2FE', 200: '#BAE6FD', 300: '#7DD3FC',
        400: '#38BDF8', 500: '#0EA5E9', 600: '#0284C7', 700: '#0369A1',
        800: '#075985', 900: '#0C4A6E',
      },
    },
    accent: {
      value: '#F97316',
      role: 'Accent highlight color',
      usage: 'Attention indicators, highlights, warm contrast',
      contrastWith: ['#FFFFFF'],
    },
    background: {
      value: '#F0FDFA',
      role: 'Page background',
      usage: 'Main page background, content area behind cards',
    },
    surface: {
      value: '#FFFFFF',
      role: 'Card and panel surface',
      usage: 'Cards, panels, modals, dropdowns, table rows',
    },
    surfaceAlt: {
      value: '#F0F9FF',
      role: 'Alternate surface',
      usage: 'Alternating table rows, code blocks, input backgrounds',
    },
    border: {
      value: '#CCFBF1',
      role: 'Standard border',
      usage: 'Card borders, input borders, dividers, table borders',
    },
    borderLight: {
      value: '#E0F2FE',
      role: 'Subtle border',
      usage: 'Light separators, hover state borders',
    },
    text: {
      primary: {
        value: '#134E4A',
        role: 'Primary text',
        usage: 'Headings, body text, labels',
      },
      secondary: {
        value: '#0F766E',
        role: 'Secondary text',
        usage: 'Descriptions, secondary labels, timestamps',
      },
      muted: {
        value: '#5EEAD4',
        role: 'Muted text',
        usage: 'Placeholders, disabled text, captions',
      },
      inverse: {
        value: '#FFFFFF',
        role: 'Inverse text',
        usage: 'Text on dark/primary backgrounds',
      },
    },
    semantic: {
      success: {
        value: '#059669',
        role: 'Success state',
        usage: 'Success badges, positive indicators, confirmations',
      },
      warning: {
        value: '#D97706',
        role: 'Warning state',
        usage: 'Warning badges, caution indicators, pending states',
      },
      error: {
        value: '#DC2626',
        role: 'Error state',
        usage: 'Error badges, destructive actions, validation errors',
      },
      info: {
        value: '#0284C7',
        role: 'Info state',
        usage: 'Info badges, informational messages, help text',
      },
    },
  },

  typography: {
    fonts: {
      heading: {
        family: 'DM Sans',
        fallback: 'system-ui, -apple-system, sans-serif',
        role: 'Headings only — H1 through H3',
        weights: [600, 700],
      },
      body: {
        family: 'DM Sans',
        fallback: 'system-ui, -apple-system, sans-serif',
        role: 'Body text, labels, descriptions',
        weights: [400, 500, 600],
      },
      mono: {
        family: 'Fira Code',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Code, data, timestamps',
        weights: [400, 500],
      },
    },
    scale: {
      xs: { size: '11px', lineHeight: '16px' },
      sm: { size: '13px', lineHeight: '20px' },
      base: { size: '15px', lineHeight: '24px' },
      lg: { size: '17px', lineHeight: '28px' },
      xl: { size: '20px', lineHeight: '30px' },
      '2xl': { size: '24px', lineHeight: '32px' },
      '3xl': { size: '30px', lineHeight: '38px' },
      '4xl': { size: '36px', lineHeight: '44px' },
    },
  },

  spacing: {
    baseUnit: '4px',
    scale: {
      '0.5': '2px', '1': '4px', '1.5': '6px', '2': '8px', '2.5': '10px', '3': '12px', '4': '16px',
      '5': '20px', '6': '24px', '8': '32px', '10': '40px',
      '12': '48px', '16': '64px', '20': '80px',
    },
    layout: {
      sidebarWidth: '256px',
      sidebarCollapsedWidth: '64px',
      topNavHeight: '60px',
      contentMaxWidth: '1280px',
      pagePadding: '32px',
    },
  },

  radius: {
    none: '0px',
    sm: { value: '6px', usage: 'Badges, tags, small chips' },
    md: { value: '10px', usage: 'Inputs, buttons, small cards' },
    lg: { value: '14px', usage: 'Cards, panels, dropdowns' },
    xl: { value: '20px', usage: 'Modals, large containers' },
    '2xl': { value: '28px', usage: 'Feature sections, hero blocks' },
    full: { value: '9999px', usage: 'Pills, avatars, toggles' },
  },

  shadows: {
    none: { value: 'none', usage: 'Flat elements' },
    sm: { value: '0 1px 3px rgba(13,148,136,0.08)', usage: 'Subtle elevation' },
    md: { value: '0 4px 8px -1px rgba(13,148,136,0.12)', usage: 'Raised cards' },
    lg: { value: '0 12px 20px -4px rgba(13,148,136,0.15)', usage: 'Floating elements' },
    xl: { value: '0 24px 32px -8px rgba(13,148,136,0.18)', usage: 'Modals, overlays' },
    overlay: {
      value: '0 0 0 1px rgba(13,148,136,0.08), 0 30px 60px -15px rgba(12,74,110,0.25)',
      usage: 'Full overlay shadow',
    },
  },

  motion: {
    duration: {
      instant: '50ms',
      fast: '100ms',
      normal: '200ms',
      slow: '350ms',
      deliberate: '500ms',
    },
    easing: {
      standard: { value: 'cubic-bezier(0.4, 0, 0.2, 1)', feel: 'Smooth, neutral' },
      enter: { value: 'cubic-bezier(0, 0, 0.2, 1)', feel: 'Decelerate in' },
      exit: { value: 'cubic-bezier(0.4, 0, 1, 1)', feel: 'Accelerate out' },
      spring: { value: 'cubic-bezier(0.34, 1.56, 0.64, 1)', feel: 'Slight overshoot' },
    },
  },

  components: {
    button: {
      primary: {
        background: '#0D9488',
        color: '#FFFFFF',
        border: 'none',
        borderRadius: '10px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '600',
        hoverBackground: '#0F766E',
        hoverColor: '#FFFFFF',
        activeBackground: '#115E59',
        disabledBackground: '#99F6E4',
        disabledColor: '#FFFFFF',
      },
      secondary: {
        background: '#FFFFFF',
        color: '#134E4A',
        border: '1px solid #CCFBF1',
        borderRadius: '10px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '500',
        hoverBackground: '#F0FDFA',
        hoverColor: '#134E4A',
        activeBackground: '#CCFBF1',
        disabledBackground: '#F0FDFA',
        disabledColor: '#5EEAD4',
      },
      ghost: {
        background: 'transparent',
        color: '#0F766E',
        border: 'none',
        borderRadius: '10px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '500',
        hoverBackground: '#F0FDFA',
        hoverColor: '#134E4A',
        activeBackground: '#CCFBF1',
        disabledBackground: 'transparent',
        disabledColor: '#5EEAD4',
      },
      danger: {
        background: '#DC2626',
        color: '#FFFFFF',
        border: 'none',
        borderRadius: '10px',
        padding: '10px 20px',
        fontSize: '15px',
        fontWeight: '600',
        hoverBackground: '#B91C1C',
        hoverColor: '#FFFFFF',
        activeBackground: '#991B1B',
        disabledBackground: '#FCA5A5',
        disabledColor: '#FFFFFF',
      },
    },
    input: {
      background: '#FFFFFF',
      color: '#134E4A',
      border: '1px solid #CCFBF1',
      borderFocus: '1px solid #0D9488',
      borderRadius: '10px',
      padding: '10px 14px',
      placeholder: '#5EEAD4',
      fontSize: '15px',
    },
    card: {
      background: '#FFFFFF',
      border: '1px solid #CCFBF1',
      borderRadius: '14px',
      shadow: '0 1px 3px rgba(13,148,136,0.08)',
      padding: '24px',
    },
    badge: {
      borderRadius: '9999px',
      padding: '2px 10px',
      fontSize: '12px',
      fontWeight: '500',
    },
    sidebar: {
      background: '#FFFFFF',
      color: '#0F766E',
      activeBackground: '#F0FDFA',
      activeColor: '#0D9488',
      hoverBackground: '#F0FDFA',
      borderRight: '1px solid #CCFBF1',
    },
    topNav: {
      background: '#FFFFFF',
      color: '#134E4A',
      borderBottom: '1px solid #CCFBF1',
      shadow: '0 1px 3px rgba(13,148,136,0.08)',
    },
    table: {
      headerBackground: '#F0FDFA',
      headerColor: '#0F766E',
      rowBackground: '#FFFFFF',
      rowAltBackground: '#F0FDFA',
      rowHoverBackground: '#CCFBF1',
      borderColor: '#CCFBF1',
    },
    dropdown: {
      background: '#FFFFFF',
      border: '1px solid #CCFBF1',
      shadow: '0 12px 20px -4px rgba(13,148,136,0.15)',
      itemHover: '#F0FDFA',
      borderRadius: '10px',
    },
    modal: {
      background: '#FFFFFF',
      overlayBackground: 'rgba(12,74,110,0.5)',
      borderRadius: '20px',
      shadow: '0 24px 32px -8px rgba(13,148,136,0.18)',
    },
    tooltip: {
      background: '#0C4A6E',
      color: '#FFFFFF',
      borderRadius: '8px',
    },
  },

  aiInstructions: {
    summary: 'A calming teal and deep blue theme inspired by the ocean. Cool tones create a serene atmosphere with warm coral accents for emphasis.',
    personality: ['calm', 'cool', 'professional', 'refreshing'],
    doList: [
      'Apply all color tokens as CSS custom properties on :root',
      'Use heading font only for H1–H3, never for body copy',
      'Respect component-level overrides over generic token inference',
      'Maintain the elevation system — do not invent additional shadow values',
    ],
    dontList: [
      'Do not mix light and dark surface tokens',
      'Do not use the primary color for destructive actions — use semantic.error',
      'Do not apply border-radius.full to rectangular layout containers',
    ],
    cssVariableMapping: {
      '--color-primary': '{colors.primary.value}',
      '--color-bg': '{colors.background.value}',
      '--color-surface': '{colors.surface.value}',
      '--color-border': '{colors.border.value}',
      '--color-text': '{colors.text.primary.value}',
      '--color-text-muted': '{colors.text.muted.value}',
      '--font-heading': '{typography.fonts.heading.family}',
      '--font-body': '{typography.fonts.body.family}',
      '--font-mono': '{typography.fonts.mono.family}',
      '--radius-md': '{radius.md.value}',
      '--shadow-md': '{shadows.md.value}',
      '--motion-normal': '{motion.duration.normal}',
      '--motion-easing': '{motion.easing.standard.value}',
    },
  },
};
