import type { Theme } from '@/types/theme';

export const terminal84Theme: Theme = {
  id: 'terminal84',
  name: 'Terminal 84',
  description: 'Cyan phosphor on black. CRT scanlines, glowing borders, and the hum of a 1984 mainframe. Retro-futurism meets surveillance state.',
  version: '1.0.0',
  author: 'AI/UI Lab',
  dateAdded: '2026-03-27',
  personality: ['retro', 'cyberpunk', 'terminal', 'neon'],
  useCases: ['Developer tools', 'Monitoring dashboards', 'Retro UIs', 'Cyberpunk apps'],

  structure: {
    backgroundTexture: 'repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0, 255, 208, 0.015) 2px, rgba(0, 255, 208, 0.015) 4px)',
    sectionGap: '20px',
    contentRadius: '0px',
  },

  colors: {
    primary: {
      value: '#00FFD0',
      role: 'Main interactive color',
      usage: 'Primary buttons, active nav items, focused inputs, links',
      contrastWith: ['#000000', '#0A0A0A'],
      shades: {
        50: '#E6FFF9', 100: '#B3FFED', 200: '#80FFE1',
        300: '#4DFFD5', 400: '#1AFFC9', 500: '#00FFD0',
        600: '#00D4AD', 700: '#00A88A', 800: '#007D67',
        900: '#005244',
      },
    },
    secondary: {
      value: '#00C8A4',
      role: 'Secondary interactive color',
      usage: 'Secondary buttons, emphasis text, accents',
      contrastWith: ['#000000'],
      shades: {
        50: '#E6FFF9', 100: '#B3FFED', 200: '#80FFE1',
        300: '#4DFFD5', 400: '#1AFFC9', 500: '#00FFD0',
        600: '#00D4AD', 700: '#00A88A', 800: '#007D67',
        900: '#005244',
      },
    },
    accent: {
      value: '#FF3333',
      role: 'Accent / warning highlight',
      usage: 'Error states, alerts, critical warnings — the red text on the CRT',
      contrastWith: ['#000000'],
    },
    background: {
      value: '#000000',
      role: 'Page background',
      usage: 'Main page background — the void behind the phosphor',
    },
    surface: {
      value: '#0A0F0D',
      role: 'Card and panel surface',
      usage: 'Cards, panels, modals — a faintly tinted black',
    },
    surfaceAlt: {
      value: '#0F1A16',
      role: 'Alternate surface',
      usage: 'Alternating table rows, code blocks, input backgrounds',
    },
    border: {
      value: '#00FFD0',
      role: 'Standard border',
      usage: 'Card borders, input borders — the glowing grid lines',
    },
    borderLight: {
      value: '#003D30',
      role: 'Subtle border',
      usage: 'Light separators, dimmed grid lines',
    },
    text: {
      primary: {
        value: '#00FFD0',
        role: 'Primary text',
        usage: 'Headings, body text, labels — the phosphor glow',
      },
      secondary: {
        value: '#00C8A4',
        role: 'Secondary text',
        usage: 'Descriptions, secondary labels, timestamps',
      },
      muted: {
        value: '#006B55',
        role: 'Muted text',
        usage: 'Placeholders, disabled text, dim phosphor',
      },
      inverse: {
        value: '#000000',
        role: 'Inverse text',
        usage: 'Text on cyan/primary backgrounds',
      },
    },
    semantic: {
      success: {
        value: '#00FFD0',
        role: 'Success state',
        usage: 'Success badges, positive indicators — same as primary phosphor',
      },
      warning: {
        value: '#FFD000',
        role: 'Warning state',
        usage: 'Warning badges, caution indicators',
      },
      error: {
        value: '#FF3333',
        role: 'Error state',
        usage: 'Error badges, destructive actions — the red alert',
      },
      info: {
        value: '#00C8A4',
        role: 'Info state',
        usage: 'Info badges, informational messages',
      },
    },
  },

  typography: {
    fonts: {
      heading: {
        family: 'VT323',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Headings — retro pixel bitmap terminal font',
        weights: [400],
      },
      body: {
        family: 'Share Tech Mono',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Body text — retro monospaced but readable',
        weights: [400],
      },
      mono: {
        family: 'Share Tech Mono',
        fallback: 'ui-monospace, SFMono-Regular, monospace',
        role: 'Code, data, timestamps',
        weights: [400, 500],
      },
    },
    scale: {
      xs: { size: '12px', lineHeight: '18px' },
      sm: { size: '14px', lineHeight: '20px' },
      base: { size: '16px', lineHeight: '24px' },
      lg: { size: '18px', lineHeight: '26px' },
      xl: { size: '22px', lineHeight: '30px' },
      '2xl': { size: '26px', lineHeight: '34px' },
      '3xl': { size: '32px', lineHeight: '40px' },
      '4xl': { size: '40px', lineHeight: '48px' },
    },
  },

  spacing: {
    baseUnit: '4px',
    scale: {
      '0.5': '2px', '1': '4px', '1.5': '6px', '2': '8px', '2.5': '10px', '3': '12px', '4': '16px',
      '5': '20px', '6': '24px', '8': '32px', '10': '40px',
      '12': '48px', '16': '64px', '20': '80px',
    },
    layout: {
      sidebarWidth: '220px',
      sidebarCollapsedWidth: '56px',
      topNavHeight: '48px',
      contentMaxWidth: '1280px',
      pagePadding: '24px',
    },
  },

  radius: {
    none: '0px',
    sm: { value: '0px', usage: 'No rounding — hard terminal edges' },
    md: { value: '0px', usage: 'No rounding — hard terminal edges' },
    lg: { value: '2px', usage: 'Barely perceptible rounding on containers' },
    xl: { value: '2px', usage: 'Barely perceptible rounding on containers' },
    '2xl': { value: '2px', usage: 'Barely perceptible rounding on containers' },
    full: { value: '9999px', usage: 'Pills, avatars, toggles' },
  },

  shadows: {
    none: { value: 'none', usage: 'Flat elements' },
    sm: { value: '0 0 4px rgba(0, 255, 208, 0.15)', usage: 'Subtle cyan glow' },
    md: { value: '0 0 8px rgba(0, 255, 208, 0.2)', usage: 'Medium cyan glow' },
    lg: { value: '0 0 16px rgba(0, 255, 208, 0.25)', usage: 'Strong cyan glow' },
    xl: { value: '0 0 24px rgba(0, 255, 208, 0.3)', usage: 'Intense cyan glow' },
    overlay: {
      value: '0 0 0 1px #00FFD0, 0 0 20px rgba(0, 255, 208, 0.2)',
      usage: 'Full overlay glow',
    },
  },

  motion: {
    duration: {
      instant: '0ms',
      fast: '50ms',
      normal: '100ms',
      slow: '200ms',
      deliberate: '300ms',
    },
    easing: {
      standard: { value: 'linear', feel: 'Instant, mechanical — CRT refresh' },
      enter: { value: 'linear', feel: 'Instant in' },
      exit: { value: 'linear', feel: 'Instant out' },
      spring: { value: 'linear', feel: 'No bounce — terminals dont bounce' },
    },
  },

  components: {
    button: {
      primary: {
        background: '#00FFD0',
        color: '#000000',
        border: '1px solid #00FFD0',
        borderRadius: '0px',
        padding: '8px 16px',
        fontSize: '13px',
        fontWeight: '700',
        hoverBackground: '#000000',
        hoverColor: '#00FFD0',
        activeBackground: '#0F1A16',
        disabledBackground: '#003D30',
        disabledColor: '#006B55',
      },
      secondary: {
        background: 'transparent',
        color: '#00FFD0',
        border: '1px solid #00FFD0',
        borderRadius: '0px',
        padding: '8px 16px',
        fontSize: '13px',
        fontWeight: '600',
        hoverBackground: '#0A0F0D',
        hoverColor: '#00FFD0',
        activeBackground: '#0F1A16',
        disabledBackground: 'transparent',
        disabledColor: '#006B55',
      },
      ghost: {
        background: 'transparent',
        color: '#00C8A4',
        border: 'none',
        borderRadius: '0px',
        padding: '8px 16px',
        fontSize: '13px',
        fontWeight: '500',
        hoverBackground: '#0A0F0D',
        hoverColor: '#00FFD0',
        activeBackground: '#0F1A16',
        disabledBackground: 'transparent',
        disabledColor: '#006B55',
      },
      danger: {
        background: '#FF3333',
        color: '#000000',
        border: '1px solid #FF3333',
        borderRadius: '0px',
        padding: '8px 16px',
        fontSize: '13px',
        fontWeight: '700',
        hoverBackground: '#000000',
        hoverColor: '#FF3333',
        activeBackground: '#0F1A16',
        disabledBackground: '#003D30',
        disabledColor: '#006B55',
      },
    },
    input: {
      background: '#000000',
      color: '#00FFD0',
      border: '1px solid #00FFD0',
      borderFocus: '1px solid #00FFD0',
      borderRadius: '0px',
      padding: '8px 12px',
      placeholder: '#006B55',
      fontSize: '13px',
    },
    card: {
      background: '#0A0F0D',
      border: '1px solid #003D30',
      borderRadius: '0px',
      shadow: 'none',
      padding: '20px',
      hoverEffect: 'glow',
    },
    badge: {
      borderRadius: '0px',
      padding: '2px 8px',
      fontSize: '11px',
      fontWeight: '700',
    },
    sidebar: {
      background: '#000000',
      color: '#00C8A4',
      activeBackground: 'transparent',
      activeColor: '#00FFD0',
      activeBorder: '1px solid #00FFD0',
      activeStyle: 'outlined',
      hoverBackground: '#0A0F0D',
      borderRight: '1px solid #003D30',
      navItemRadius: '0px',
      navGap: '2px',
    },
    topNav: {
      background: '#000000',
      color: '#00FFD0',
      borderBottom: '1px solid #003D30',
      shadow: 'none',
    },
    table: {
      headerBackground: '#0A0F0D',
      headerColor: '#00FFD0',
      rowBackground: '#000000',
      rowAltBackground: '#0A0F0D',
      rowHoverBackground: '#0F1A16',
      borderColor: '#003D30',
    },
    dropdown: {
      background: '#0A0F0D',
      border: '1px solid #00FFD0',
      shadow: '0 0 8px rgba(0, 255, 208, 0.2)',
      itemHover: '#0F1A16',
      borderRadius: '0px',
    },
    modal: {
      background: '#0A0F0D',
      overlayBackground: 'rgba(0,0,0,0.85)',
      borderRadius: '0px',
      shadow: '0 0 24px rgba(0, 255, 208, 0.3)',
    },
    tooltip: {
      background: '#00FFD0',
      color: '#000000',
      borderRadius: '0px',
    },
  },

  aiInstructions: {
    summary: 'A cyan phosphor terminal theme inspired by 1984 mainframes. Black background, cyan glow, CRT scanline texture, monospaced everything, sharp corners.',
    personality: ['retro', 'cyberpunk', 'terminal', 'neon'],
    doList: [
      'Apply all color tokens as CSS custom properties on :root',
      'Use monospace fonts for everything — headings, body, and code',
      'Keep all border radii at 0 — hard terminal edges',
      'Use cyan glow shadows instead of traditional elevation',
      'Buttons should invert on hover (cyan bg → black bg with cyan text)',
      'The scanline texture on the background is part of the aesthetic',
    ],
    dontList: [
      'Do not use rounded corners — this is a hard-edge terminal',
      'Do not use any color outside the cyan/teal spectrum (except red for errors/warnings)',
      'Do not use serif or sans-serif fonts — monospace only',
      'Do not use soft, diffused shadows — either no shadow or a cyan glow',
    ],
    cssVariableMapping: {
      '--color-primary': '{colors.primary.value}',
      '--color-bg': '{colors.background.value}',
      '--color-surface': '{colors.surface.value}',
      '--color-border': '{colors.border.value}',
      '--color-text': '{colors.text.primary.value}',
      '--color-text-muted': '{colors.text.muted.value}',
      '--font-heading': '{typography.fonts.heading.family}',
      '--font-body': '{typography.fonts.body.family}',
      '--font-mono': '{typography.fonts.mono.family}',
      '--radius-md': '{radius.md.value}',
      '--shadow-md': '{shadows.md.value}',
      '--motion-normal': '{motion.duration.normal}',
      '--motion-easing': '{motion.easing.standard.value}',
    },
  },
};
